=== bibletime/historic-bibletime.info/schema/dtd/autolayout.dtd
<!-- ====================================================================== -->
<!-- Website Autolayout DTD V2.5.0
     Part of the Website distribution
     http://sourceforge.net/projects/docbook/

     Please use the following formal public identifier to identify it:

     "-//Norman Walsh//DTD Website Autolayout V2.5.0//EN"

     For example:

     <!DOCTYPE autolayout PUBLIC "-//Norman Walsh//DTD Website Autolayout V2.5.0//EN"
               "http://docbook.sourceforge.net/release/website/2.5.0/autolayout.dtd">

     Please direct all questions and comments about this DTD to
     Norman Walsh, <ndw@nwalsh.com>.
                                                                            -->
<!-- ====================================================================== -->

<!ELEMENT autolayout ((copyright|style|script|headlink|config)*, toc+, notoc*)>

<!ELEMENT toc (title, titleabbrev?, summary?, tocentry*)>
<!ATTLIST toc
	id		ID	#REQUIRED
	page		CDATA	#REQUIRED
	dir		CDATA	#IMPLIED
	filename	CDATA	#REQUIRED
>

<!ELEMENT title ANY>

<!ELEMENT titleabbrev ANY>

<!ELEMENT summary (#PCDATA)*>

<!ELEMENT config EMPTY>
<!ATTLIST config
	param	CDATA	#REQUIRED
	value	CDATA	#REQUIRED
	altval	CDATA	#IMPLIED
>

<!ELEMENT style (#PCDATA)>
<!ATTLIST style
	src	CDATA	#IMPLIED
	type	CDATA	#IMPLIED
>

<!ELEMENT script (#PCDATA)>
<!ATTLIST script
	src	CDATA	#IMPLIED
	language	CDATA	#IMPLIED
	type	CDATA	#IMPLIED
>

<!ELEMENT headlink EMPTY>
<!ATTLIST headlink
	href	CDATA	#IMPLIED
	media	CDATA	#IMPLIED
	name	CDATA	#IMPLIED
	rel	CDATA	#IMPLIED
	rev	CDATA	#IMPLIED
	src	CDATA	#IMPLIED
	title	CDATA	#IMPLIED
	type	CDATA	#IMPLIED
>

<!ELEMENT copyright (year+, holder+)>

<!ELEMENT year (#PCDATA)*>

<!ELEMENT holder (#PCDATA|ulink)*>
<!ATTLIST holder
	role	CDATA	#IMPLIED
>

<!ELEMENT ulink (#PCDATA)*>
<!ATTLIST ulink
	url	CDATA	#REQUIRED
>

<!ELEMENT tocentry (title, titleabbrev?, summary?, tocentry*)>
<!ATTLIST tocentry
	id		ID	#REQUIRED
	page		CDATA	#IMPLIED
	href		CDATA	#IMPLIED
	dir		CDATA	#IMPLIED
	filename	CDATA	#IMPLIED
	revisionflag	(added|changed)	#IMPLIED
	tocskip		(0|1)	"0"
>

<!ELEMENT notoc (title, titleabbrev?, summary?)>
<!ATTLIST notoc
	id		ID	#REQUIRED
	page		CDATA	#REQUIRED
	dir		CDATA	#IMPLIED
	filename	CDATA	#REQUIRED
>

<!-- End of autolayout.dtd V2.5.0 ......................................... -->
<!-- ...................................................................... -->

=== bibletime/historic-bibletime.info/pt-br/autolayout.xml
<?xml version="1.0"?>
<!DOCTYPE autolayout PUBLIC "-//Norman Walsh//DTD Website Autolayout V2.4.1//EN" "http://docbook.sourceforge.net/release/website/2.4.1/schema/dtd/autolayout.dtd">
<autolayout>
<style title="Blue" src="blue.css" type="text/css"/><copyright><year>1999</year><year>2000</year><year>2001</year><year>2002</year><year>2003</year><year>2004</year><holder role="http://www.bibletime.info/">Desenvolvedores do BibleTime - www.bibletime.info</holder></copyright><notoc page="error404.xml" id="error404" filename="error404.html">
<title>Erro</title>
<summary>Error 404: File not found</summary>
</notoc>
<toc page="index.xml" id="index" filename="no_index.html">
<title>BibleTime</title>
<summary>Introduction</summary>
<tocentry page="software.xml" id="software" filename="index.html">
<title>Software</title>
<summary>Introduction</summary>
<tocentry page="software_about.xml" id="software_about" filename="software_about.html">
<title>Sobre o BibleTime</title>
<summary>Introduction to the BibleTime software</summary>
</tocentry>
<tocentry page="software_screenshots.xml" id="software_screenshots" filename="software_screenshots.html">
<title>Telas</title>
<summary>Screenshots of BibleTime</summary>
</tocentry>
<tocentry page="software_gallery.xml" id="software_gallery" filename="software_gallery.html">
<title>Galeria</title>
<summary>Gallery of BibleTime</summary>
</tocentry>
<tocentry page="software_installation.xml" id="documentation_installation_bibletime" filename="software_installation.html">
<title>Download</title>
<summary>Installation to the BibleTime software</summary>
</tocentry>
<tocentry page="software_faq.xml" id="documentation_ifaq" filename="software_faq.html">
<title>Perguntas Frequentes</title>
<summary>FAQ about BibleTime</summary>
</tocentry>
<tocentry page="software_swordcd.xml" id="software_swordcd" filename="software_swordcd.shtml">
<title>CD do Sword</title>
<summary>Get the Sword CD</summary>
</tocentry>
<tocentry page="software_links.xml" id="software_links" filename="software_links.html">
<title>Links</title>
<summary>Link collection of good sites</summary>
</tocentry>
<tocentry page="software_linkus.xml" id="software_linkus" filename="software_linkus.html">
<title>Link para n&#xF3;s</title>
<summary>How to link to www.bibletime.info</summary>
</tocentry>
<tocentry page="software_guestbook.xml" id="software_guestbook" filename="software_guestbook.shtml">
<title>Livro de Visitas</title>
<summary>BibleTime's guestbook</summary>
</tocentry>
<tocentry page="software_press.xml" id="software_press" filename="software_press.html">
<title>Na m&#xED;dia</title>
<summary>BibleTime in the press</summary>
</tocentry>
<tocentry page="software_contact.xml" id="contact" filename="software_contact.html">
<title>Contato</title>
<summary>How to contact us</summary>
</tocentry>
<tocentry page="software_license.xml" id="software_license" filename="software_license.html">
<title>Licen&#xE7;a</title>
<summary>BibleTime's license</summary>
</tocentry>
</tocentry>
<tocentry page="development.xml" id="development" filename="development.html">
<title>Desenvolvimento</title>
<summary>BibleTime's development</summary>
<tocentry page="development_help.xml" id="development_help" filename="development_help.html">
<title>Nos ajude</title>
<summary>BibleTime's development</summary>
</tocentry>
<tocentry page="development_join.xml" id="development_join" filename="development_join.html">
<title>Junte-se a n&#xF3;s</title>
<summary>BibleTime's development</summary>
</tocentry>
<tocentry page="development_mailinglists.xml" id="development_mailinglists" filename="development_mailinglists.html">
<title>Listas de discuss&#xE3;o</title>
<summary>BibleTime's mailinglists</summary>
</tocentry>
</tocentry>
<tocentry page="translation.xml" id="translation" filename="translation.shtml">
<title>Tradu&#xE7;&#xE3;o</title>
<summary>Introduction</summary>
</tocentry>
<tocentry page="biblehowto.docbook" id="biblehowto" filename="biblehowto.html">
<title>Estudo B&#xED;blico HowTo</title>
<summary>The BibleTime Biblestudy HowTo</summary>
</tocentry>
</toc>
</autolayout>

=== bibletime/historic-bibletime.info/ru/autolayout.xml
<?xml version="1.0"?>
<!DOCTYPE autolayout PUBLIC "-//Norman Walsh//DTD Website Autolayout V2.4.1//EN" "http://docbook.sourceforge.net/release/website/2.4.1/schema/dtd/autolayout.dtd">
<autolayout>
<style title="Blue" src="blue.css" type="text/css"/><style title="Plain" src="plain.css" type="text/css"/><config param="text-prefix" value="txt_"/><copyright
><year
>1999</year
><year
>2000</year
><year
>2001</year
><year
>2002</year
><year
>2003</year
><holder role="http://www.bibletime.info/"
></holder
></copyright
><notoc page="error404.xml" id="error404" filename="error404.html">
<title
></title>
<summary
>Error 404: File not found</summary>
</notoc>
<toc page="index.xml" id="index" filename="no_index.html">
<title
>О BibleTime</title>
<summary
>Introduction</summary>
<tocentry page="software.xml" id="software" filename="index.html">
<title
>Приложения</title>
<summary
>Introduction</summary>
<tocentry page="software_about.xml" id="software_about" filename="software_about.html">
<title
>О BibleTime</title>
<summary
>Introduction to the BibleTime software</summary>
</tocentry>
<tocentry page="software_screenshots.xml" id="software_screenshots" filename="software_screenshots.html">
<title
>Скриншоты</title>
<summary
>Screenshots of BibleTime</summary>
</tocentry>
<tocentry page="software_download.xml" id="software_download" filename="software_download.html">
<title
>Загрузить ПО</title>
<summary
>Download BibleTime</summary>
</tocentry>
<tocentry page="software_press.xml" id="software_press" filename="software_press.html">
<title
>Пресса о нас</title>
<summary
>BibleTime in the press</summary>
</tocentry>
<tocentry page="software_contact.xml" id="contact" filename="software_contact.html">
<title
>Напиши нам</title>
<summary
>How to contact us</summary>
</tocentry>
<tocentry page="software_guestbook.xml" id="software_guestbook" filename="software_guestbook.shtml">
<title
>Гостевая книга</title>
<summary
>BibleTime's guestbook</summary>
</tocentry>
<tocentry page="software_links.xml" id="software_links" filename="software_links.html">
<title
>Ссылки</title>
<summary
>Link collection of good sites</summary>
</tocentry>
<tocentry page="software_linkus.xml" id="software_linkus" filename="software_linkus.html">
<title
>Ссылка к нам</title>
<summary
>How to link to www.bibletime.info</summary>
</tocentry>
<tocentry page="software_license.xml" id="software_license" filename="software_license.html">
<title
>Лицензия</title>
<summary
>BibleTime's license</summary>
</tocentry>
</tocentry>
<tocentry page="documentation.xml" id="documentation" filename="documentation.html">
<title
>Документация</title>
<summary
>Introduction</summary>
<tocentry page="documentation_requirements.xml" id="documentation_requirements_bibletime" filename="documentation_requirements.html">
<title
>Требования к системе</title>
<summary
>Introduction to the BibleTime software</summary>
</tocentry>
<tocentry page="documentation_installation.xml" id="documentation_installation" filename="documentation_installation.html" tocskip="1">
<title
>Установка</title>
<summary
>Introduction to the BibleTime software</summary>
<tocentry page="documentation_installation_bibletime.xml" id="documentation_installation_bibletime" filename="documentation_installation_bibletime.html">
<title
>О BibleTime</title>
<summary
>Introduction to the BibleTime software</summary>
</tocentry>
<tocentry page="documentation_installation_sword.xml" id="documentation_installation_sword" filename="documentation_installation_sword.html">
<title
></title>
<summary
>How to install Swors</summary>
</tocentry>
<tocentry page="documentation_installation_modules.xml" id="documentation_installation_modules" filename="documentation_installation_modules.html">
<title
>Модули</title>
<summary
>How to install Sword modules</summary>
</tocentry>
</tocentry>
<tocentry page="documentation_faq.xml" id="documentation_ifaq" filename="documentation_faq.html">

<summary
>FAQ about BibleTime</summary>
</tocentry>
</tocentry>
<tocentry page="modules.xml" id="modules" filename="modules.html">
<title
>Модули</title>
<summary
>Introduction to Sword modules</summary>
<tocentry page="modules_swordcd.xml" id="modules_swordcd" filename="modules_swordcd.shtml">
<title
>Sword на CD</title>
<summary
>Get the Sword CD</summary>
</tocentry>
</tocentry>
<tocentry page="development.xml" id="development" filename="development.html">
<title
>Разработка ПО</title>
<summary
>BibleTime's development</summary>
<tocentry page="development_help.xml" id="development_help" filename="development_help.html">
<title
>Если хочешь помочь</title>
<summary
>BibleTime's development</summary>
</tocentry>
<tocentry page="development_join.xml" id="development_join" filename="development_join.html">
<title
></title>
<summary
>BibleTime's development</summary>
</tocentry>
<tocentry page="development_mailinglists.xml" id="development_mailinglists" filename="development_mailinglists.html">
<title
>Рассылки</title>
<summary
>BibleTime's mailinglists</summary>
</tocentry>
</tocentry>
<tocentry page="biblehowto.docbook" id="biblehowto" filename="biblehowto.html">
<title
>Как изучать Библию</title>
<summary
>The BibleTime Biblestudy HowTo</summary>
</tocentry>
</toc>
</autolayout>

=== bibletime/historic-bibletime.info/ro/autolayout.xml
<?xml version="1.0"?>
<!DOCTYPE autolayout PUBLIC "-//Norman Walsh//DTD Website Autolayout V2.4.1//EN" "http://docbook.sourceforge.net/release/website/2.4.1/schema/dtd/autolayout.dtd">
<autolayout>
<style title="Blue" src="blue.css" type="text/css"/><style title="Plain" src="plain.css" type="text/css"/><config param="text-prefix" value="txt_"/><copyright><year>1999</year><year>2000</year><year>2001</year><year>2002</year><year>2003</year><holder role="http://www.bibletime.info/">The BibleTime developers - <ulink url="http://www.bibletime.info/">www.bibletime.info</ulink></holder></copyright><toc page="index.xml" id="index" filename="no_index.html">
<title>Despre BibleTime</title>
<summary>Introduction</summary>
<tocentry page="software.xml" id="software" filename="index.html">
<title>Aplicatia</title>
<summary>Introduction</summary>
<tocentry page="software_about.xml" id="software_about" filename="software_about.html">
<title>Despre BibleTime</title>
<summary>Introduction to the BibleTime software</summary>
</tocentry>
<tocentry page="software_news.xml" id="software_news" filename="software_news.html">
<title>Noutati</title>
<summary>News about BibleTime</summary>
</tocentry>
<tocentry page="software_screenshots.xml" id="software_screenshots" filename="software_screenshots.html">
<title>Imagini</title>
<summary>Screenshots of BibleTime</summary>
</tocentry>
<tocentry page="software_download.xml" id="software_download" filename="software_download.html">
<title>Descarca</title>
<summary>Download BibleTime</summary>
</tocentry>
<tocentry page="software_press.xml" id="software_press" filename="software_press.html">
<title>Din presa</title>
<summary>BibleTime in the press</summary>
</tocentry>
<tocentry page="software_contact.xml" id="contact" filename="software_contact.html">
<title>Contact</title>
<summary>How to contact us</summary>
</tocentry>
<tocentry page="software_guestbook.xml" id="software_guestbook" filename="software_guestbook.shtml">
<title>Carte de oaspeti</title>
<summary>BibleTime's guestbook</summary>
</tocentry>
<tocentry page="software_links.xml" id="software_links" filename="software_links.html">
<title>Legaturi</title>
<summary>Link collection of good sites</summary>
</tocentry>
<tocentry page="software_linkus.xml" id="software_linkus" filename="software_linkus.html">
<title>Legatura spre noi</title>
<summary>How to link to www.bibletime.info</summary>
</tocentry>
<tocentry page="software_license.xml" id="software_license" filename="software_license.html">
<title>Licenta</title>
<summary>BibleTime's license</summary>
</tocentry>
</tocentry>
<tocentry page="documentation.xml" id="documentation" filename="documentation.html">
<title>Documentatie</title>
<summary>Introduction</summary>
<tocentry page="documentation_requirements.xml" id="documentation_requirements_bibletime" filename="documentation_requirements.html">
<title>Cerinte</title>
<summary>Introduction to the BibleTime software</summary>
</tocentry>
<tocentry page="documentation_installation.xml" id="documentation_installation" filename="documentation_installation.html" tocskip="1">
<title>Instalare</title>
<summary>Introduction to the BibleTime software</summary>
<tocentry page="documentation_installation_bibletime.xml" id="documentation_installation_bibletime" filename="documentation_installation_bibletime.html">
<title>Despre BibleTime</title>
<summary>Introduction to the BibleTime software</summary>
</tocentry>
<tocentry page="documentation_installation_sword.xml" id="documentation_installation_sword" filename="documentation_installation_sword.html">
<title>Sword</title>
<summary>How to install Swors</summary>
</tocentry>
<tocentry page="documentation_installation_modules.xml" id="documentation_installation_modules" filename="documentation_installation_modules.html">
<title>Module</title>
<summary>How to install Sword modules</summary>
</tocentry>
</tocentry>
<tocentry page="documentation_faq.xml" id="documentation_ifaq" filename="documentation_faq.html">
<title>FAQ</title>
<summary>FAQ about BibleTime</summary>
</tocentry>
</tocentry>
<tocentry page="modules.xml" id="modules" filename="modules.html">
<title>Module</title>
<summary>Introduction to Sword modules</summary>
<tocentry page="modules_swordcd.xml" id="modules_swordcd" filename="modules_swordcd.shtml">
<title>Obtine Cd-ul Sword</title>
<summary>Get the Sword CD</summary>
</tocentry>
</tocentry>
<tocentry page="development.xml" id="development" filename="development.html">
<title>Dezvoltare</title>
<summary>BibleTime's development</summary>
<tocentry page="development_help.xml" id="development_help" filename="development_help.html">
<title>Cum sa ne ajuti</title>
<summary>BibleTime's development</summary>
</tocentry>
<tocentry page="development_join.xml" id="development_join" filename="development_join.html">
<title>Join us</title>
<summary>BibleTime's development</summary>
</tocentry>
<tocentry page="development_mailinglists.xml" id="development_mailinglists" filename="development_mailinglists.html">
<title>Mailing lists</title>
<summary>BibleTime's mailinglists</summary>
</tocentry>
</tocentry>
<tocentry page="biblehowto.docbook" id="biblehowto" filename="biblehowto.html">
<title>Biblestudy HowTo</title>
<summary>The BibleTime Biblestudy HowTo</summary>
</tocentry>
</toc>
</autolayout>

=== bibletime/historic-bibletime.info/ua/autolayout.xml
<?xml version="1.0"?>
<!DOCTYPE autolayout PUBLIC "-//Norman Walsh//DTD Website Autolayout V2.4.1//EN" "http://docbook.sourceforge.net/release/website/2.4.1/schema/dtd/autolayout.dtd">
<autolayout>
<style title="Blue" src="blue.css" type="text/css"/><style title="Plain" src="plain.css" type="text/css"/><config param="text-prefix" value="txt_"/><copyright><year>1999</year><year>2000</year><year>2001</year><year>2002</year><year>2003</year><holder role="http://www.bibletime.info/">The BibleTime developers - www.bibletime.info</holder></copyright><toc page="index.xml" id="index" filename="no_index.html">
<title/>
<summary>Introduction</summary>
<tocentry page="software.xml" id="software" filename="index.html">
<title>&#x41F;&#x440;&#x43E;&#x433;&#x440;&#x430;&#x43C;&#x438;</title>
<summary>Introduction</summary>
<tocentry page="software_about.xml" id="software_about" filename="software_about.html">
<title>&#x429;&#x43E;&#x434;&#x43E; BibleTime</title>
<summary>Introduction to the BibleTime software</summary>
</tocentry>
<tocentry page="software_news.xml" id="software_news" filename="software_news.html">
<title>&#x41D;&#x43E;&#x432;&#x438;&#x43D;&#x438;</title>
<summary>News about BibleTime</summary>
</tocentry>
<tocentry page="software_screenshots.xml" id="software_screenshots" filename="software_screenshots.html">
<title>&#x421;&#x43A;&#x440;&#x456;&#x43D;&#x448;&#x43E;&#x442;&#x438;</title>
<summary>Screenshots of BibleTime</summary>
</tocentry>
<tocentry page="software_download.xml" id="software_download" filename="software_download.html">
<title>&#x417;&#x430;&#x432;&#x430;&#x43D;&#x442;&#x430;&#x436;&#x438;&#x442;&#x438;</title>
<summary>Download BibleTime</summary>
</tocentry>
<tocentry page="software_press.xml" id="software_press" filename="software_press.html">
<title>&#x423; &#x43F;&#x440;&#x435;&#x441;&#x456;</title>
<summary>BibleTime in the press</summary>
</tocentry>
<tocentry page="software_contact.xml" id="contact" filename="software_contact.html">
<title>&#x41F;&#x438;&#x448;&#x456;&#x442;&#x44C; &#x43D;&#x430;&#x43C;</title>
<summary>How to contact us</summary>
</tocentry>
<tocentry page="software_guestbook.xml" id="software_guestbook" filename="software_guestbook.shtml">
<title>&#x413;&#x43E;&#x441;&#x442;&#x44C;&#x43E;&#x432;&#x430; &#x43A;&#x43D;&#x438;&#x433;&#x430;</title>
<summary>BibleTime's guestbook</summary>
</tocentry>
<tocentry page="software_links.xml" id="software_links" filename="software_links.html">
<title>&#x41F;&#x43E;&#x441;&#x438;&#x43B;&#x430;&#x43D;&#x43D;&#x44F;</title>
<summary>Link collection of good sites</summary>
</tocentry>
<tocentry page="software_linkus.xml" id="software_linkus" filename="software_linkus.html">
<title>&#x41F;&#x43E;&#x441;&#x438;&#x43B;&#x430;&#x43D;&#x43D;&#x44F; &#x43D;&#x430; &#x43D;&#x430;&#x441;</title>
<summary>How to link to www.bibletime.info</summary>
</tocentry>
<tocentry page="software_license.xml" id="software_license" filename="software_license.html">
<title>&#x41B;&#x456;&#x446;&#x435;&#x43D;&#x437;&#x456;&#x44F;</title>
<summary>BibleTime's license</summary>
</tocentry>
</tocentry>
<tocentry page="documentation.xml" id="documentation" filename="documentation.html">
<title>&#x414;&#x43E;&#x43A;&#x443;&#x43C;&#x435;&#x43D;&#x442;&#x430;&#x446;&#x456;&#x44F;</title>
<summary>Introduction</summary>
<tocentry page="documentation_requirements.xml" id="documentation_requirements_bibletime" filename="documentation_requirements.html">
<title>&#x412;&#x438;&#x43C;&#x43E;&#x433;&#x438; &#x434;&#x43E; &#x441;&#x438;&#x441;&#x442;&#x435;&#x43C;&#x438;</title>
<summary>Introduction to the BibleTime software</summary>
</tocentry>
<tocentry page="documentation_installation.xml" id="documentation_installation" filename="documentation_installation.html" tocskip="1">
<title>Installation</title>
<summary>Introduction to the BibleTime software</summary>
<tocentry page="documentation_installation_bibletime.xml" id="documentation_installation_bibletime" filename="documentation_installation_bibletime.html">
<title>&#x429;&#x43E;&#x434;&#x43E; BibleTime</title>
<summary>Introduction to the BibleTime software</summary>
</tocentry>
<tocentry page="documentation_installation_sword.xml" id="documentation_installation_sword" filename="documentation_installation_sword.html">
<title>Sword</title>
<summary>How to install Swors</summary>
</tocentry>
<tocentry page="documentation_installation_modules.xml" id="documentation_installation_modules" filename="documentation_installation_modules.html">
<title>&#x41C;&#x43E;&#x434;&#x443;&#x43B;&#x456;</title>
<summary>How to install Sword modules</summary>
</tocentry>
</tocentry>
<tocentry page="documentation_faq.xml" id="documentation_ifaq" filename="documentation_faq.html">
<title>FAQ</title>
<summary>FAQ about BibleTime</summary>
</tocentry>
</tocentry>
<tocentry page="modules.xml" id="modules" filename="modules.html">
<title>&#x41C;&#x43E;&#x434;&#x443;&#x43B;&#x456;</title>
<summary>Introduction to Sword modules</summary>
<tocentry page="modules_swordcd.xml" id="modules_swordcd" filename="modules_swordcd.shtml">
<title>Sword CD</title>
<summary>Get the Sword CD</summary>
</tocentry>
</tocentry>
<tocentry page="development.xml" id="development" filename="development.html">
<title>&#x420;&#x43E;&#x437;&#x440;&#x43E;&#x431;&#x43A;&#x430; &#x41F;&#x417;</title>
<summary>BibleTime's development</summary>
<tocentry page="development_help.xml" id="development_help" filename="development_help.html">
<title>Help us</title>
<summary>BibleTime's development</summary>
</tocentry>
<tocentry page="development_join.xml" id="development_join" filename="development_join.html">
<title>Join us</title>
<summary>BibleTime's development</summary>
</tocentry>
<tocentry page="development_mailinglists.xml" id="development_mailinglists" filename="development_mailinglists.html">
<title>Mailinglists</title>
<summary>BibleTime's mailinglists</summary>
</tocentry>
</tocentry>
<tocentry page="biblehowto.docbook" id="biblehowto" filename="biblehowto.html">
<title>Biblestudy HowTo</title>
<summary>The BibleTime Biblestudy HowTo</summary>
</tocentry>
</toc>
</autolayout>

=== bibletime/historic-bibletime.info/fr/autolayout.xml
<?xml version="1.0"?>
<!DOCTYPE autolayout PUBLIC "-//Norman Walsh//DTD Website Autolayout V2.4.1//EN" "http://docbook.sourceforge.net/release/website/2.4.1/schema/dtd/autolayout.dtd">
<autolayout>
<style title="Blue" src="blue.css" type="text/css"/><copyright><year>1999</year><year>2000</year><year>2001</year><year>2002</year><year>2003</year><year>2004</year><holder role="http://www.bibletime.info/">Les d&#xE9;veloppeurs BibleTime - www.bibletime.info</holder></copyright><notoc page="error404.xml" id="error404" filename="error404.html">
<title>Erreur</title>
<summary>Error 404: File not found</summary>
</notoc>
<toc page="index.xml" id="index" filename="no_index.html">
<title>BibleTime</title>
<summary>Introduction</summary>
<tocentry page="software.xml" id="software" filename="index.html">
<title>Logiciel</title>
<summary>Introduction</summary>
<tocentry page="software_about.xml" id="software_about" filename="software_about.html">
<title>A propos de BibleTime</title>
<summary>Introduction to the BibleTime software</summary>
</tocentry>
<tocentry page="software_screenshots.xml" id="software_screenshots" filename="software_screenshots.html">
<title>Captures &#xE9;cran</title>
<summary>Screenshots of BibleTime</summary>
</tocentry>
<tocentry page="software_gallery.xml" id="software_gallery" filename="software_gallery.html">
<title>Gallery</title>
<summary>Gallery of BibleTime</summary>
</tocentry>
<tocentry page="software_installation.xml" id="documentation_installation_bibletime" filename="software_installation.html">
<title>T&#xE9;l&#xE9;chargement</title>
<summary>Installation to the BibleTime software</summary>
</tocentry>
<tocentry page="software_faq.xml" id="documentation_ifaq" filename="software_faq.html">
<title>FAQ</title>
<summary>FAQ about BibleTime</summary>
</tocentry>
<tocentry page="software_swordcd.xml" id="software_swordcd" filename="software_swordcd.shtml">
<title>CD Sword</title>
<summary>Get the Sword CD</summary>
</tocentry>
<tocentry page="software_links.xml" id="software_links" filename="software_links.html">
<title>Liens</title>
<summary>Link collection of good sites</summary>
</tocentry>
<tocentry page="software_linkus.xml" id="software_linkus" filename="software_linkus.html">
<title>Liens vers nous</title>
<summary>How to link to www.bibletime.info</summary>
</tocentry>
<tocentry page="software_guestbook.xml" id="software_guestbook" filename="software_guestbook.shtml">
<title>Livre d'or</title>
<summary>BibleTime's guestbook</summary>
</tocentry>
<tocentry page="software_press.xml" id="software_press" filename="software_press.html">
<title>Dans la presse</title>
<summary>BibleTime in the press</summary>
</tocentry>
<tocentry page="software_contact.xml" id="contact" filename="software_contact.html">
<title>Contact</title>
<summary>How to contact us</summary>
</tocentry>
<tocentry page="software_license.xml" id="software_license" filename="software_license.html">
<title>License</title>
<summary>BibleTime's license</summary>
</tocentry>
</tocentry>
<tocentry page="development.xml" id="development" filename="development.html">
<title>D&#xE9;veloppement</title>
<summary>BibleTime's development</summary>
<tocentry page="development_help.xml" id="development_help" filename="development_help.html">
<title>Aidez-nous</title>
<summary>BibleTime's development</summary>
</tocentry>
<tocentry page="development_join.xml" id="development_join" filename="development_join.html">
<title>Joignez-nous</title>
<summary>BibleTime's development</summary>
</tocentry>
<tocentry page="development_mailinglists.xml" id="development_mailinglists" filename="development_mailinglists.html">
<title>Forums</title>
<summary>BibleTime's mailinglists</summary>
</tocentry>
</tocentry>
<tocentry page="translation.xml" id="translation" filename="translation.shtml">
<title>Traduction</title>
<summary>Introduction</summary>
</tocentry>
<tocentry page="biblehowto.docbook" id="biblehowto" filename="biblehowto.html">
<title>HowTo d'&#xE9;tude biblique</title>
<summary>The BibleTime Biblestudy HowTo</summary>
</tocentry>
</toc>
</autolayout>
