=== bibletime/historic-bibletime.info/schema/dtd/layout.dtd
<!-- ====================================================================== -->
<!-- Website Layout DTD V2.5.0
     Part of the Website distribution
     http://sourceforge.net/projects/docbook/

     Please use the following formal public identifier to identify it:

     "-//Norman Walsh//DTD Website Layout V2.5.0//EN"

     For example:

     <!DOCTYPE layout PUBLIC "-//Norman Walsh//DTD Website Layout V2.5.0//EN"
                     "http://docbook.sourceforge.net/release/website/2.5.0/layout.dtd">

     Please direct all questions and comments about this DTD to
     Norman Walsh, <ndw@nwalsh.com>.
                                                                            -->
<!-- ====================================================================== -->

<!ELEMENT layout ((config|style|script|headlink|copyright)*, toc+, notoc*)>

<!ELEMENT config EMPTY>
<!ATTLIST config
	param	CDATA	#REQUIRED
	value	CDATA	#REQUIRED
	altval	CDATA	#IMPLIED
>

<!ELEMENT style (#PCDATA)>
<!ATTLIST style
	src	CDATA	#IMPLIED
	type	CDATA	#IMPLIED
>

<!ELEMENT script (#PCDATA)>
<!ATTLIST script
	src	CDATA	#IMPLIED
	language	CDATA	#IMPLIED
	type	CDATA	#IMPLIED
>

<!ELEMENT headlink EMPTY>
<!ATTLIST headlink
	href	CDATA	#IMPLIED
	media	CDATA	#IMPLIED
	name	CDATA	#IMPLIED
	rel	CDATA	#IMPLIED
	rev	CDATA	#IMPLIED
	src	CDATA	#IMPLIED
	title	CDATA	#IMPLIED
	type	CDATA	#IMPLIED
>

<!ELEMENT copyright (year+, holder+)>

<!ELEMENT year (#PCDATA)*>

<!ELEMENT holder (#PCDATA|ulink)*>
<!ATTLIST holder
	role	CDATA	#IMPLIED
>

<!ELEMENT ulink (#PCDATA)*>
<!ATTLIST ulink
	url	CDATA	#REQUIRED
>

<!ELEMENT toc (tocentry*)>
<!ATTLIST toc
	page		CDATA	#REQUIRED
	dir		CDATA	#IMPLIED
	filename	CDATA	#IMPLIED
>

<!ELEMENT tocentry ((title|titleabbrev|summary)*, tocentry*)>
<!ATTLIST tocentry
	id		ID	#IMPLIED
	page		CDATA	#IMPLIED
	href		CDATA	#IMPLIED
	dir		CDATA	#IMPLIED
	filename	CDATA	#IMPLIED
	revisionflag	(added|changed)	#IMPLIED
	tocskip		(0|1)	"0"
>

<!ELEMENT notoc EMPTY>
<!ATTLIST notoc
	page		CDATA	#REQUIRED
	dir		CDATA	#IMPLIED
	filename	CDATA	#IMPLIED
>

<!ELEMENT title ANY>

<!ELEMENT titleabbrev ANY>

<!ELEMENT summary (#PCDATA)*>

<!-- End of layout.dtd V2.5.0 ............................................. -->
<!-- ...................................................................... -->

=== bibletime/historic-bibletime.info/ro/layout.xml
<?xml version="1.0"?>
<!DOCTYPE layout PUBLIC "-//Norman Walsh//DTD Website Layout V2.4.0//EN"
          "../schema/dtd/layout.dtd">
<layout>
  <style title="Blue" src="blue.css" type="text/css"
></style>

	<copyright>
    <year
>1999</year>
		<year
>2000</year>
		<year
>2001</year>
		<year
>2002</year>
		<year
>2003</year>
		<year
>2004</year>
    <holder role="http://www.bibletime.info/"
>The BibleTime developers - www.bibletime.info</holder>
  </copyright>

  <notoc page="error404.xml" filename="error404.html"
></notoc>

  <toc page="index.xml" filename="no_index.html">
		<tocentry page="software.xml" filename="index.html">
			<tocentry page="software_about.xml" filename="software_about.html"
></tocentry>
			<tocentry page="software_screenshots.xml" filename="software_screenshots.html"
></tocentry>
			<tocentry page="software_gallery.xml" filename="software_gallery.html"
></tocentry>
			<tocentry page="software_installation.xml" filename="software_installation.html"
></tocentry>
			<tocentry page="software_faq.xml" filename="software_faq.html"
></tocentry>
			<tocentry page="software_swordcd.xml" filename="software_swordcd.shtml"
></tocentry>
			<tocentry page="software_links.xml" filename="software_links.html"
></tocentry>
			<tocentry page="software_linkus.xml" filename="software_linkus.html"
></tocentry>
			<tocentry page="software_guestbook.xml" filename="software_guestbook.shtml"
></tocentry>
			<tocentry page="software_press.xml" filename="software_press.html"
></tocentry>
			<tocentry page="software_contact.xml" filename="software_contact.html"
></tocentry>
			<tocentry page="software_license.xml" filename="software_license.html"
></tocentry>
		</tocentry>

		<tocentry page="development.xml" filename="development.html">
			<tocentry page="development_help.xml" filename="development_help.html"
></tocentry>
			<tocentry page="development_join.xml" filename="development_join.html"
></tocentry>
			<tocentry page="development_mailinglists.xml" filename="development_mailinglists.html"
></tocentry>
	  </tocentry>

		<tocentry page="translation.xml" filename="translation.shtml"
></tocentry>

		<tocentry page="biblehowto.docbook" filename="biblehowto.html"
></tocentry>

	</toc>
</layout>

=== bibletime/historic-bibletime.info/ko/layout.xml
<?xml version="1.0"?>
<!DOCTYPE layout PUBLIC "-//Norman Walsh//DTD Website Layout V2.4.0//EN"
          "../en/schema/dtd/layout.dtd">
<layout>
  <style title="Blue" src="blue.css" type="text/css"/>

	<copyright>
    <year
>1999</year>
		<year
>2000</year>
		<year
>2001</year>
		<year
>2002</year>
		<year
>2003</year>
    <holder role="http://www.bibletime.info/"
>바이블타임 개발자 - www.bibletime.info</holder>
  </copyright>

  <notoc page="error404.xml" filename="error404.html"/>
	<notoc page="translation.xml" filename="translation.shtml"/>

  <toc page="index.xml" filename="no_index.html">
		<tocentry page="software.xml" filename="index.html">
			<tocentry page="software_about.xml" filename="software_about.html"/>
			<tocentry page="software_screenshots.xml" filename="software_screenshots.html"/>
			<tocentry page="software_gallery.xml" filename="software_gallery.html"/>
			<tocentry page="software_download.xml" filename="software_download.html"/>
			<tocentry page="software_press.xml" filename="software_press.html"/>
			<tocentry page="software_contact.xml" filename="software_contact.html"/>
			<tocentry page="software_guestbook.xml" filename="software_guestbook.shtml"/>
			<tocentry page="software_links.xml" filename="software_links.html"/>
			<tocentry page="software_linkus.xml" filename="software_linkus.html"/>
			<tocentry page="software_license.xml" filename="software_license.html"/>
		</tocentry>

		<tocentry page="documentation.xml" filename="documentation.html">
			<tocentry page="documentation_requirements.xml" filename="documentation_requirements.html"/>
			<tocentry tocskip="1" page="documentation_installation.xml" filename="documentation_installation.html">
				<tocentry page="documentation_installation_bibletime.xml" filename="documentation_installation_bibletime.html"/>
				<tocentry page="documentation_installation_sword.xml" filename="documentation_installation_sword.html"/>
				<tocentry page="documentation_installation_modules.xml" filename="documentation_installation_modules.html"/>
			</tocentry>
			<tocentry page="documentation_faq.xml" filename="documentation_faq.html"/>
		</tocentry>

		<tocentry page="modules.xml" filename="modules.html">
			<tocentry page="modules_swordcd.xml" filename="modules_swordcd.shtml"/>
	  </tocentry>

		<tocentry page="development.xml" filename="development.html">
			<tocentry page="development_help.xml" filename="development_help.html"/>
			<tocentry page="development_join.xml" filename="development_join.html"/>
			<tocentry page="development_mailinglists.xml" filename="development_mailinglists.html"/>
	  </tocentry>

		<tocentry page="biblehowto.docbook" filename="biblehowto.html"/>

	</toc>
</layout>
